name: DevOps Learning Pipeline

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: Create website package
        run: zip -r website.zip index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-package
          path: website.zip